config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to =>'homes#top' # アプリケーショントップ画面をルートパスへ
  get 'books'=>'books#index'
  post 'books'=>'books#create'
  # books/1や.../books/3に該当する
  get 'books/:id'=>'books#show', as: 'book'
  get 'books/:id/edit'=>'books#edit',as: 'edit-book'
  patch 'books/:id' => 'books#update',as: 'update-book'
  delete 'books/:id' => 'books#destroy',as: 'destroy-book'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book =Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice: 'Book was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      redirect_to books_path,notice: 'Book was successfully destroyed'
    else
      render :index
    end
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<!--投稿編集画面-->
<h1>Editing Book</h1>

<!--バリデーションによる空白チェック-->
<% if @book.errors.any? %>
 <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
     <ul>
         <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
    </ul>
<% end %>


<%= form_with model: @book,url: update_book_path(@book.id),method: :patch,local:true do |f| %>
<!--本のタイトルの編集-->
<div class=field>
  <%= f.label :Title %>
  <%= f.text_field :title%>
</div>
<!--本の感想の編集-->
<div class=field>
  <%= f.label :Body %>
  <%= f.text_field :body%>
</div>
<!--投稿内容の更新-->
<%= f.submit "Update Book" %>
<% end %>

<p><%= link_to "Show",book_path %> | <%= link_to "Back",books_path %></p>

app/views/books/index.html.erb
<%= notice %>

<!--タイトル-->
<h1>Books</h1>
<table>
  <!--表のヘッダ部分-->
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <!--表のボディ部分-->
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show",book_path(book.id)%></td>
      <td><%= link_to "Edit",edit_book_path(book.id)%></td>
      <td><%= link_to "Destroy",destroy_book_path(book.id),method: :delete,"data-confirm" => "Are you sure?"%></td>
    </tr>
    <% end %>
  </tbody>
</table>



<!--新規投稿-->
<h2>New book</h2>

<!--バリデーションによる空白チェック-->
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
   <ul>
     <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
    </ul>
  <% end %>

<%= form_with model: @book, url: "/books",method: :post,local:true do |f| %>
  <!--新規投稿する本のタイトル-->
  <div class=field>
    <%= f.label :Title %>
    <%= f.text_field :title %>
  </div>
  <!--新規投稿する本の感想-->
  <div class=field>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <!--投稿ボタン（CreateBook）-->
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<%= notice %>

<!--id=○のタイトル-->
<p>Title:<%= @book.title %></p>
<!--id=○の感想-->
<p>Body:<%= @book.body %></p>

<p><%= link_to "Edit",edit_book_path %> | <%= link_to "Back",books_path %></p>

app/views/homes/top.html.erb
<!--Top画面-->
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p>Bookersでは、さまざまな書籍に関するあなたの意見を</p>

<p>印象を共有し、交換することができます</p>

<p><%= link_to "Start", books_path %></p>

 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>